### ISSUE TITLE
Have to install 9Anime and AnimeOnsen extensions to use them on every Aniyomi launch

### ISSUE THREAD

**Issue by SoumyBhow** [jmir1/aniyomi-mpv-beta#19]
Hello,
Recently I've noticed that the anime extensions AnimeOnsen and 9Anime have some issues. Everytime I open Aniyomi, these two sources don't show up as installed, even though they are. I always have to "install" them in order to use them. If I quit Aniyomi and open again, the same thing happens and I have to tap install for them. Is there any fix?
![Screenshot_20220821-035759_Aniyomi](https://user-images.githubusercontent.com/42043870/185781626-f839c7a7-797e-4037-8200-ab952832af31.png)

**Comment by jmir1** [comment]
I'm aware of this, it happens because 9anime tries to generate the encryption and decryption keys on startup and animeonsen tries to generate the oauth token on startup. I need to change this behaviour so this is only done when they are needed because this will fail on app startup because the dependencies aren't injected yet (at least that's my guess).

So basically, I know how to fix it, I just haven't had the time to do it yet.

**Comment by SoumyBhow** [comment]
Oh dear. I realize someone already reported on this on the original Aniyomi repo [here](https://github.com/jmir1/aniyomi/issues/721). My sincere apologies. Either or, thank you for your input. I'll wait till a fix is released. Out of curiosity, is the same problem happening for AnimeOnsen as well or no?

**Comment by jmir1** [comment]
no problem, thanks anyway for reporting the issue.
as i said in my comment, it is basically the same issue for both extensions.
im gonna fix it real quick

**Comment by jmir1** [comment]
i have fixed it with new updates to both extensions.

**Comment by SoumyBhow** [comment]
Perfect thank you very much!
